on:
  workflow_dispatch:

jobs:
  my_job:
      runs-on: ubuntu-latest
      name: testing components
      steps:
      - uses: actions/checkout@v4.1.0
        with: 
          repository: COBA-NIH/MicroscopyForBeginnersReferenceGuide
